package:
  name: edipack
  version: "2.0"

source:
  git_url: https://github.com/EDIpack/EDIpack2.0.git

requirements:
  build:
    - pkg-config
    - cmake
    - make
    - ninja
    - meson
    - meson-python 
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi
    - libgfortran-ng=13  # [linux]
    - mpi
  host:
    - python
    - meson-python 
    - pip
    - numpy
    - mpi4py
    - mkl  # [linux]
    - mkl-devel  # [linux]
    - mkl-include  # [linux]
    - openblas  # [osx]
    - lapack  # [osx]
  run:
    - python
    - numpy
    - mpi4py
    - openmpi
    - mkl  # [linux]
    - openblas  # [osx]
    - lapack  # [osx]

about:
  home: https://github.com/EDIpack/EDIpack2.0
  license: MIT
  summary: "EDIpack - Fortran library for electronic structure calculations"
  description: |
    EDIpack is a library for stuff,
    requiring SciFortran and various numerical libraries.
  dev_url: https://github.com/EDIpack/EDIpack2.0

