package:
  name: edipack
  version: "0.0.1"

source:
  git_url: https://github.com/EDIpack/EDIpack.git

requirements:
  build:
    - pkg-config
    - setuptools
    - wheel
    - cmake
    - make
    - ninja
    - meson
    - meson-python 
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - openmpi
    - libgfortran-ng=13  # [linux]
    - mpi
  host:
    - python
    - meson-python 
    - pip
    - setuptools
    - wheel
    - numpy
    - openmpi
    - mpi4py
    - mkl <2025 # [linux]
    - mkl-devel <2025  # [linux]
    - mkl-include <2025 # [linux]
    - openblas  # [osx]
    - lapack  # [osx]
    - scalapack  # [osx]
  run:
    - python
    - numpy
    - mpi4py
    - openmpi
    - pkg-config
    - mkl <2025 # [linux]
    - openblas  # [osx]
    - lapack  # [osx]
    - scalapack  # [osx]

about:
  home: https://github.com/EDIpack/EDIpack
  license: MIT
  summary: "EDIpack quantum impurity solver"
  description: |
    EDIpack is a massively parallel Lanczos-based quantum impurity solver
  dev_url: https://github.com/EDIpack/EDIpack

