context:
  name: edipack2
  version: "0.0.1"
  python: "3.13"
  number: "0"

package:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: ${{ number }}
  string: py${{ python | replace(".", "") }}${{ hash }}_${{ number }}


requirements:
  build:
    - pkg-config
    - python=${{ python }}
    - cmake
    - make
    - ninja
    - meson
    - meson-python
    - ${{ compiler("c") }}
    - ${{ compiler("fortran") }}
    - openmpi
    - mpi
    - if: linux
      then:
        - libgfortran-ng  # [linux]
  host:
    - python=${{ python }}
    - pkgconfig #the python module
    - meson-python
    - pip
    - numpy
    - openmpi
    - mpi4py
    - if: linux
      then:
        - mkl <2025  # [linux]
        - mkl-devel <2025  # [linux]
        - mkl-include <2025  # [linux]
    - if: osx
      then:
        - openblas  # [osx]
        - lapack  # [osx]
        - scalapack  # [osx]
  run:
    - python=${{ python }}
    - pkgconfig #the python module
    - numpy
    - mpi4py
    - openmpi
    - if: linux
      then:
        - mkl <2025  # [linux]
    - if: osx
      then:
        - openblas  # [osx]
        - lapack  # [osx]
        - scalapack  # [osx]

about:
  repository: https://github.com/EDIpack/EDIpack2.0
  license: GPL-3.0-or-later
  license_url: https://raw.githubusercontent.com/EDIpack/EDIpy2.0/refs/heads/main/LICENSE.txt
  summary: "EDIpack2.0 quantum impurity solver"
  description: |
    EDIpack2.0 is a massively parallel Lanczos-based quantum impurity solver.

