name: Build and Upload Conda Package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        #python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        python-version: ["3.12"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          activate-environment: build-env
          python-version: ${{ matrix.python-version }}

      - name: Install build dependencies
        run: conda install -y conda-build anaconda-client

      - name: Build Conda Package
        run: conda build . --python=${{ matrix.python-version }}

      - name: Upload to Anaconda
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        run: |
          anaconda upload --user lcrippa $(conda build . --python=${{ matrix.python-version }} --output)

