name: Build and Upload Conda Package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.12"]
    env:
      ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          channels: conda-forge
          python-version: 3.12
        #miniforge-version: "latest"

      - name: Create and activate build environment  # 🔹 New step
        run: |
          conda create -n build-env python=${{ matrix.python-version }} conda-build anaconda-client -y
          echo "CONDA_ENV=build-env" >> $GITHUB_ENV

      - name: Build Conda Package
        id: build
        run: |
          # Build using the output folder and override the Python variant to the one in the matrix
          source activate $CONDA_ENV
          conda build -c conda-forge recipe/ --output-folder output
          # Get the path to the built package from the output folder
          BUILT_PKG=$(conda build -c conda-forge recipe/ --output-folder output --output)
          echo "Built package: ${BUILT_PKG}"
          echo "BUILT_PKG=${BUILT_PKG}" >> $GITHUB_ENV

      - name: Upload package to Anaconda
        shell: "bash -l {0}"
        run: |
          conda init bash
          source ~/.bashrc
          conda activate $CONDA_ENV
          conda install -y conda-build anaconda-client
          echo "Uploading ${BUILT_PKG} to Anaconda..."
          anaconda upload --user lcrippa "${BUILT_PKG}"
        continue-on-error: true
