name: Build and Upload Conda Package

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-file: environment.yml
          cache-environment: true
          cache-downloads: true

      - name: Install Conda Build and dependencies
        shell: bash -l {0}
        run: |
          micromamba install -y conda-build anaconda-client

      - name: Build Conda Package
        shell: bash -l {0}
        run: conda build . --python=${{ matrix.python-version }}

      - name: Upload to Anaconda
        if: github.event_name == 'push' && matrix.os == 'ubuntu-latest'
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_API_TOKEN }}
        shell: bash -l {0}
        run: |
          conda install -y anaconda-client
          anaconda upload --user lcrippa $(conda build . --python=${{ matrix.python-version }} --output)
