name: Test a build


on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANACONDA_API_KEY: ${{ secrets.ANACONDA_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build in CentOS 7-compatible container
        run: |
          docker run --rm \
            -v "$PWD":/io \
            -w /io \
            quay.io/pypa/manylinux2014_x86_64 bash -c '

              echo "Installing rattler-build inside manylinux2014..."
              yum install -y python3 python3-pip git jq curl sed
              pip3 install rattler-build

              echo "Fetching latest tag..."
              LATEST_TAG=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                "https://api.github.com/repos/edipack/edipack/git/refs/tags" | \
                jq -r ".[].ref" | sed "s#refs/tags/##" | sort -V | grep -v "^v" | tail -n 1)
              echo "Latest tag: $LATEST_TAG"

              echo "Patching recipe..."
              sed -i "3s/0\\.0\\.1/${LATEST_TAG}/g" recipe_rattler/recipe.yaml
              sed -i "4s/3\\.13/3.11/g" recipe_rattler/recipe.yaml

              echo "Running rattler-build..."
              rattler-build build --recipe recipe_rattler/recipe.yaml --output-folder output
            '

      - name: Upload built package to Anaconda
        run: |
          PKG=$(find output -type f -name "*.conda" -o -name "*.tar.bz2")
          echo "Built package: $PKG"
          rattler-build upload anaconda -f -o edipack "$PKG"
